trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_REGISTRY_CONNECTION: 'ACR'
  IMAGE_REGISTRY: 'acrdev001jsb'
  IMAGE_REPOSITORY: 'acrdev001jsb.azurecr.io'
  TAG: '$(Build.BuildId)'
  AZURE_SUBSCRIPTION: 'ADO'

stages:
- stage: BuildApp 
  jobs:
    - job: BuildPushImage
      steps: 
      - task: Docker@2
        inputs:
          containerRegistry: '$(IMAGE_REGISTRY_CONNECTION)'
          repository: '$(IMAGE_REPOSITORY)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(TAG)'
            
- stage: DeployDev
  jobs:
    - job: DeployDev
      steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: '$(AZURE_SUBSCRIPTION)'
            appType: 'webAppContainer'
            WebAppName: 'webappcontainerjsb001'
            DockerNamespace: '$(IMAGE_REGISTRY)'
            DockerRepository: '$(IMAGE_REPOSITORY)'
            DockerImageTag: '$(TAG)'